src/AppBundle/Entity/File.php
<?php

namespace AppBundle\Entity;

/**
 * File
 */
class File
{
    /**
     * @var guid
     */
    private $fileID;

    /**
     * @var string
     */
    private $name;

    /**
     * @var string
     */
    private $extension;

    /**
     * @var \DateTime
     */
    private $creationDate;

    /**
     * @var \DateTime
     */
    private $lastModifiedDate;

    /**
     * @var \DateTime
     */
    private $lastAccessDate;

    /**
     * @var \Doctrine\Common\Collections\Collection
     */
    private $childs;

    /**
     * @var \AppBundle\Entity\Folder
     */
    private $folder;

    /**
     * @var \AppBundle\Entity\User
     */
    private $owner;

    /**
     * @var \AppBundle\Entity\Entity
     */
    private $entity;

    /**
     * @var \AppBundle\Entity\File
     */
    private $parent;

    /**
     * @var \AppBundle\Entity\User
     */
    private $lastModifiedBy;

    /**
     * @var \AppBundle\Entity\User
     */
    private $lastAccessBy;
    
    /**
     * Constructor
     */
    public function __construct()
    {
        $this->childs = new \Doctrine\Common\Collections\ArrayCollection();
    }

    /**
     * Get fileID
     *
     * @return guid
     */
    public function getFileID()
    {
        return $this->fileID;
    }

    /**
     * Set name
     *
     * @param string $name
     *
     * @return File
     */
    public function setName($name)
    {
        $this->name = $name;
    
        return $this;
    }

    /**
     * Get name
     *
     * @return string
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * Set extension
     *
     * @param string $extension
     *
     * @return File
     */
    public function setExtension($extension)
    {
        $this->extension = $extension;
    
        return $this;
    }

    /**
     * Get extension
     *
     * @return string
     */
    public function getExtension()
    {
        return $this->extension;
    }

    /**
     * Set creationDate
     *
     * @param \DateTime $creationDate
     *
     * @return File
     */
    public function setCreationDate($creationDate)
    {
        $this->creationDate = $creationDate;
    
        return $this;
    }

    /**
     * Get creationDate
     *
     * @return \DateTime
     */
    public function getCreationDate()
    {
        return $this->creationDate;
    }

    /**
     * Set lastModifiedDate
     *
     * @param \DateTime $lastModifiedDate
     *
     * @return File
     */
    public function setLastModifiedDate($lastModifiedDate)
    {
        $this->lastModifiedDate = $lastModifiedDate;
    
        return $this;
    }

    /**
     * Get lastModifiedDate
     *
     * @return \DateTime
     */
    public function getLastModifiedDate()
    {
        return $this->lastModifiedDate;
    }

    /**
     * Set lastAccessDate
     *
     * @param \DateTime $lastAccessDate
     *
     * @return File
     */
    public function setLastAccessDate($lastAccessDate)
    {
        $this->lastAccessDate = $lastAccessDate;
    
        return $this;
    }

    /**
     * Get lastAccessDate
     *
     * @return \DateTime
     */
    public function getLastAccessDate()
    {
        return $this->lastAccessDate;
    }

    /**
     * Add child
     *
     * @param \AppBundle\Entity\File $child
     *
     * @return File
     */
    public function addChild(\AppBundle\Entity\File $child)
    {
        $this->childs[] = $child;
    
        return $this;
    }

    /**
     * Remove child
     *
     * @param \AppBundle\Entity\File $child
     */
    public function removeChild(\AppBundle\Entity\File $child)
    {
        $this->childs->removeElement($child);
    }

    /**
     * Get childs
     *
     * @return \Doctrine\Common\Collections\Collection
     */
    public function getChilds()
    {
        return $this->childs;
    }

    /**
     * Set folder
     *
     * @param \AppBundle\Entity\Folder $folder
     *
     * @return File
     */
    public function setFolder(\AppBundle\Entity\Folder $folder = null)
    {
        $this->folder = $folder;
    
        return $this;
    }

    /**
     * Get folder
     *
     * @return \AppBundle\Entity\Folder
     */
    public function getFolder()
    {
        return $this->folder;
    }

    /**
     * Set owner
     *
     * @param \AppBundle\Entity\User $owner
     *
     * @return File
     */
    public function setOwner(\AppBundle\Entity\User $owner = null)
    {
        $this->owner = $owner;
    
        return $this;
    }

    /**
     * Get owner
     *
     * @return \AppBundle\Entity\User
     */
    public function getOwner()
    {
        return $this->owner;
    }

    /**
     * Set entity
     *
     * @param \AppBundle\Entity\Entity $entity
     *
     * @return File
     */
    public function setEntity(\AppBundle\Entity\Entity $entity = null)
    {
        $this->entity = $entity;
    
        return $this;
    }

    /**
     * Get entity
     *
     * @return \AppBundle\Entity\Entity
     */
    public function getEntity()
    {
        return $this->entity;
    }

    /**
     * Set parent
     *
     * @param \AppBundle\Entity\File $parent
     *
     * @return File
     */
    public function setParent(\AppBundle\Entity\File $parent = null)
    {
        $this->parent = $parent;
    
        return $this;
    }

    /**
     * Get parent
     *
     * @return \AppBundle\Entity\File
     */
    public function getParent()
    {
        return $this->parent;
    }
    /**
     * @var integer
     */
    private $size;


    /**
     * Set size
     *
     * @param integer $size
     *
     * @return File
     */
    public function setSize($size)
    {
        $this->size = $size;
    
        return $this;
    }

    /**
     * Get size
     *
     * @return integer
     */
    public function getSize()
    {
        return $this->size;
    }
    
    /**
     * Set lastModifiedBy
     *
     * @param \AppBundle\Entity\User $lastModifiedBy
     *
     * @return File
     */
    public function setLastModifiedBy(\AppBundle\Entity\User $lastModifiedBy = null)
    {
        $this->lastModifiedBy = $lastModifiedBy;

        return $this;
    }

    /**
     * Get lastModifiedBy
     *
     * @return \AppBundle\Entity\User
     */
    public function getLastModifiedBy()
    {
        return $this->lastModifiedBy;
    }

    /**
     * Set lastAccessBy
     *
     * @param \AppBundle\Entity\User $lastAccessBy
     *
     * @return File
     */
    public function setLastAccessBy(\AppBundle\Entity\User $lastAccessBy = null)
    {
        $this->lastAccessBy = $lastAccessBy;

        return $this;
    }

    /**
     * Get lastAccessBy
     *
     * @return \AppBundle\Entity\User
     */
    public function getLastAccessBy()
    {
        return $this->lastAccessBy;
    }
    
    /**
     * Propiedades Adicionales
     */
    
    /**
     * @var boolean
     */
    private $mark=false;
    /**
     * @var boolean
     */
    private $trash=false;
    /**
     * Metodos adicionales
     */
    public function getIcon(){
        $ext=$this->getExtension();
        if(in_array($ext, ['odm','odt','doc','docx'])){
            return "fa-file-word-o";
        }else if(in_array($ext, ['xls','xlsx','csv','ods','ots'])){
            return "fa-file-excel-o";
        }else if(in_array($ext, ['odp','odg','otp','ppt','pps','pptx','potx'])){
            return "fa-file-powerpoint-o";
        }else if(in_array($ext, ['txt','uot','rtf'])){
            return "fa-file-text-o";
        }else if(in_array($ext, ['tar','bz2','gz','7z','s7z','dmg','rar','zip','pea'])){
            return "fa-file-archive-o";
        }else if(in_array($ext, ['webm','mkv','flv','flv','vob','ogv','ogg','drc','mng','avi','mov','qt','wmv','yuv','rm','rmvb','asf','amv','mp4','m4v','mpg','mp2','mpeg','mpe','mpv','mpg','mpeg','m2v','m4v','svi','3gp','3g2','mxf','roq','nsv','flv','f4v','f4p','f4a','f4b'])){
            return "fa-file-video-o";
        }else if(in_array($ext, ['amr','mp1','mp2','mp3','aac','flac','wma'])){
            return "fa-file-audio-o";
        }else if(in_array($ext, ['bmp','jpeg','jpg','pcx','psd','sgv','wmf','dxf','met','pgm','svm','emf','sda','tga','eps','pcd','png','sdd','tif','tiff','gif','pct','sgf','webp'])){
            return "fa-file-image-o";
        }else if(in_array($ext, ['pdf'])){
            return "fa-file-pdf-o";
        }else {
            return "fa-file-o";
        }
    }
    
    public function setMark($mark){
        $this->mark=$mark;
    }
    
    public function getMark(){
        return $this->mark;
    }
    
    public function setTrash($trash){
        $this->trash=$trash;
    }
    
    public function getTrash(){
        return $this->trash;
    }
    public function getEncoded(){
        $data=[
            'id'=>$this->getFileID(),
            'entity'=>$this->getEntity()->getEntity()
        ];
        $json=json_encode($data,JSON_UNESCAPED_UNICODE);
        return base64_encode($json);
    }
}

src/AppBundle/Controller/MainController.php
<?php

namespace AppBundle\Controller;

use AppBundle\Entity\User;
use Doctrine\ORM\Query\ResultSetMapping;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\Extension\Core\Type\PasswordType;
use Symfony\Component\Form\Extension\Core\Type\RepeatedType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\FormError;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Security\Core\Encoder\UserPasswordEncoderInterface;

class MainController extends Controller {

    public function MainAction() {
        if (!($this->getUser() instanceof User)) {
            return $this->redirectToRoute('_login');
        }
        return $this->render('AppBundle:Main:main.html.twig', array(
                        // ...
        ));
    }

    public function StartAction() {
        $em = $this->getDoctrine()->getManager();
        $me = $this->getUser();
        $files = $me->getFavoriteFiles();
        $rsm = new ResultSetMapping();
        $rsm->addScalarResult('1', 'Result');
        foreach ($files as $file) {
            $file->setMark(true);
            $query = $em->createNativeQuery(
                    'SELECT 1 '
                    . 'FROM TRASHBIN '
                    . 'WHERE ENTITYID=? AND ENTITY=?', $rsm);
            $query->setParameter(1, $file->getFileID())->setParameter(2, $file->getEntity());
            $result = $query->getResult();
            if (count($result) > 0) {
                $file->setTrash(true);
            }
        }
        return $this->render('AppBundle:Main:favs.html.twig', array(
                    'files' => $files,
                    'uploadContext' => ''
        ));
    }

    public function DriveAction(Request $request) {
        $context = $request->request->get('uploadContext', '');
        $em = $this->getDoctrine()->getManager();
        $me = $this->getUser();
        if ($context !== '') {
            $folder = $em->find('AppBundle:Folder', $context);
            if ($folder == NULL) {
                $folder = NULL;
            } else {
                $folder = $folder->getFolderID();
            }
        } else {
            $folder = NULL;
        }
        $files = $em->getRepository('AppBundle:File')->findBy(['owner' => $me->getUsername(), 'folder' => $folder, 'parent' => NULL]);
        $rsm = new ResultSetMapping();
        $rsm->addScalarResult('1', 'Result');
        foreach ($files as $file) {
            $query = $em->createNativeQuery(
                    'SELECT 1 '
                    . 'FROM FAVORITEFILES '
                    . 'WHERE USER=? AND FILE=?', $rsm);
            $query->setParameter(1, $me->getUsername())->setParameter(2, $file->getFileID());
            $result = $query->getResult();
            if (count($result) > 0) {
                $file->setMark(true);
            }
            $query = $em->createNativeQuery(
                    'SELECT 1 '
                    . 'FROM TRASHBIN '
                    . 'WHERE ENTITYID=? AND ENTITY=?', $rsm);
            $query->setParameter(1, $file->getFileID())->setParameter(2, $file->getEntity());
            $result = $query->getResult();
            if (count($result) > 0) {
                $file->setTrash(true);
            }
        }
        return $this->render('AppBundle:Main:drive.html.twig', array(
                    'files' => $files,
                    'uploadContext' => $context
        ));
    }

    public function SharedAction(Request $request) {

        return $this->render('AppBundle:Main:shared.html.twig', array(
                        // ...
        ));
    }

    public function TrashAction() {
        $me = new User();
        $em = $this->getDoctrine()->getManager();
        $me = $this->getUser();
        $rsm = new ResultSetMapping();
        $rsm->addEntityResult('AppBundle:Trash', 't');
        $rsm->addFieldResult('t', 'trashID', 'trashID');
        $rsm->addFieldResult('t', 'entityID', 'entityID');
        $rsm->addFieldResult('t', 'liveUntil', 'liveUntil');
        $rsm->addFieldResult('t', 'deletedOn', 'deletedOn');
        $rsm->addJoinedEntityResult('AppBundle:User', 'delBy', 't', 'deletedBy');
        $rsm->addFieldResult('delBy', 'username', 'username');
        $rsm->addEntityResult('AppBundle:File', 'f');
        $rsm->addFieldResult('f', 'fileID', 'fileID');
        $rsm->addFieldResult('f', 'name', 'name');
        $rsm->addFieldResult('f', 'extension', 'extension');
        $rsm->addFieldResult('f', 'creationDate', 'creationDate');
        $rsm->addFieldResult('f', 'lastModifiedDate', 'lastModifiedDate');
        $rsm->addFieldResult('f', 'lastAccessDate', 'lastAccessDate');
        $rsm->addFieldResult('f', 'size', 'size');
        $rsm->addJoinedEntityResult('AppBundle:Entity', 'e', 'f', 'entity');
        $rsm->addFieldResult('e', 'entity', 'entity');
        $sql =    'SELECT t.trashID, t.entityID, t.liveUntil, t.deletedOn, delBy.username, '
                . 'f.fileID, f.name, f.extension, f.creationDate, f.lastModifiedDate, f.lastAccessDate, f.size, e.entity '
                . 'FROM trashbin t '
                . 'JOIN users delBy ON(t.deletedBy=delBy.username) '
                . 'JOIN files f ON(t.entityID=f.fileID) '
                . 'JOIN entities e ON(e.entity=f.entity) '
                . 'WHERE t.entity=f.entity '
                . 'AND f.owner=?';
        $query = $em->createNativeQuery($sql, $rsm);
        $query->setParameter(1, $me->getUsername());
        $result = $query->getResult();
        
        for ($i = 0; $i < count($result); $i+=2) {
            $file['trash']=$result[$i];
            $file['object']=$result[$i+1];
            $files[]=$file;
        }
        return $this->render('AppBundle:Main:trash.html.twig', array(
                    'files' => $files,
                    'uploadContext' => ''
        ));
    }

    public function ProfileAction($username = FALSE) {
        if ($username === FALSE) {
            $user = $this->getUser();
        } else {
            $query = $this->getDoctrine()->getManager()->find('AppBundle:User', $username);
            if ($query === NULL) {
                $this->createNotFoundException();
            } else {
                $user = $query;
            }
        }
        return $this->render('AppBundle:Main:Profile.html.twig', array(
                    'user' => $user,
        ));
    }

    public function EditProfileAction(Request $request, UserPasswordEncoderInterface $encoder) {
        $timezones = ['' => ''];
        foreach (timezone_identifiers_list() as $value) {
            $timezones[$value] = $value;
        }
        $form = $this->createFormBuilder()
                ->add('lastpassword', PasswordType::class)
                ->add('newpassword', RepeatedType::class, [
                    'type' => PasswordType::class,
                    'invalid_message' => 'Las contraseñas deben coincidir.',
                    'first_name' => 'newpassword',
                    'second_name' => 'confirm_newpassword',
                    'required' => false,
                ])
                ->add('timezone', ChoiceType::class, [
                    'mapped' => false,
                    'label' => 'Zona horaria',
                    'choices' => $timezones,
                    'data' => $this->getUser()->getTimezoneString()
                ])
                ->add('submit', SubmitType::class, ['label' => 'Actualizar'])
                ->getForm();
        $submitted = false;
        $form->handleRequest($request);
        if ($form->isSubmitted()) {
            $submitted = true;
            $user = $this->getUser();
            $lastpass = $form->get('lastpassword')->getData();
            if ($encoder->isPasswordValid($user, $lastpass)) {
                if ($form->isValid()) {
                    if (!$form->get('newpassword')->isEmpty()) {
                        $newpass = $encoder->encodePassword($user, $form->get('newpassword')->getData());
                        $user->setPassword($newpass);
                    }
                    $user->setTimezone($form->get('timezone')->getData());
                    $this->getDoctrine()->getManager()->persist($user);
                    $this->getDoctrine()->getManager()->flush();
                    return $this->ProfileAction();
                }
            } else {
                $form->get('lastpassword')->addError(new FormError("Contraseña incorrecta"));
            }
        }
        return $this->render('AppBundle:Main:EditProfile.html.twig', array(
                    'form' => $form->createView(),
                    'submitted' => $submitted
        ));
    }

}

src/AppBundle/Resources/views/Main/editProfile.html.twig
{% include "::api.html.twig" %}
{% form_theme form 'form/tooltipErrors.twig' %}
<script>
    var requireJS = [];

</script>



<div class="animated fadeIn">

    <div class="card">
        <div class="container p-5">
            {{ form_start(form,{'id':'register_form','action':'Editar/Perfil'}) }}
            <div class="input-group mb-3">
                <span class="input-group-addon"><i class="icon-user"></i>
                </span>
                <input class="form-control" readonly value="{{app.user.username}}">
            </div>
            <div class="input-group mb-3">
                <span class="input-group-addon">@</span>
                <input class="form-control" readonly value="{{app.user.email}}">
            </div>
            <div class="mb-4">
                {{form_widget(form.timezone, {'attr': {'errors':form_errors(form.timezone),'class': 'form-control '~(submitted==true?(form_errors(form.timezone)?'is-invalid':'is-valid'):''),'data-placeholder':'Zona Horaria','select2':'true'} })}}
            </div>
            <div class="input-group mb-3">
                <span class="input-group-addon"><i class="icon-lock"></i>
                </span>
                {{form_widget(form.lastpassword, {'attr': {'errors':form_errors(form.lastpassword),'class': 'form-control '~(submitted==true?(form_errors(form.lastpassword)?'is-invalid':'is-valid'):''),'placeholder':'Contraseña actual'} })}}
            </div>
            <span>Si no deseas cambiar tu contraseña deja estos espacios en blanco</span> 
            <div class="input-group mb-3">
                <span class="input-group-addon"><i class="icon-lock"></i>
                </span>
                {{form_widget(form.newpassword.newpassword, {'attr': {'errors':form_errors(form.newpassword.newpassword),'class': 'form-control '~(submitted==true?(form_errors(form.newpassword.newpassword)?'is-invalid':'is-valid'):''),'placeholder':'Nueva contraseña'} })}}
            </div>
            <div class="input-group mb-4">
                <span class="input-group-addon"><i class="icon-lock"></i>
                </span>
                {{form_widget(form.newpassword.confirm_newpassword, { 'attr': {'class': 'form-control '~(submitted==true?(form_errors(form.newpassword.newpassword)?'is-invalid':'is-valid'):''),'placeholder':'Repite la nueva contraseña'} })}}
            </div>
            {{form_widget(form.submit, { 'attr': {'class': 'btn btn-block btn-success'} })}}
            {{ form_end(form) }}
        </div>
    </div>
    <!--/.card-->
</div>

src/AppBundle/Resources/views/Main/favs.html.twig
{% include "::api.html.twig" %}
<script>
    var requireJS = [];
    loadJS(requireJS, "{{path('RAL',{'request':'upload.js'}) }}");
    loadJS(requireJS, "{{path('RAL',{'request':'api.js'}) }}");
</script>



<div class="animated fadeIn">

    {% if files is defined and files|length > 0 %}
        <div class="card">
            <table class="table table-responsive table-hover table-align-middle table-inverse table-striped mb-0">
                <thead class="thead-inverse">
                    <tr>
                        <th class="text-center"><i class="fa fa-lg fa-files-o"></i>
                        </th>
                        <th>Nombre</th>
                        <th class="text-center">Tamaño</th>
                        <th class="d-none d-md-table-cell">Ultimo acceso</th>
                        <th class="d-none d-md-table-cell">Ultima modificación</th>
                        <th class="text-center"><i class="icon-grid"></i></th>
                    </tr>
                </thead>
                <tbody>
                    {% for item in files %}
                        <tr>
                            <td class="text-center" ondblclick="alert('hola');">
                                <i class=" fa fa-lg {{item.icon}}"></i>
                            </td>
                            <td ondblclick="alert('hola');">
                                <div>{{item.name}}</div>
                                <div class="small text-muted">
                                    <span>Creado el: </span> {{dateHuman(item.creationDate,"d/m/Y H:i:s")}}
                                </div>
                            </td>
                            <td class="text-center">
                                <div class="callout callout-success">
                                    <strong class="h6">{{bytesConvert(item.size)}}</strong>
                                </div>
                            </td>
                            <td class="d-none d-md-table-cell">
                                <div><a href="{{path('_profile',{'username':item.lastAccessBy.username})}}">{{item.lastAccessBy.username}}</a></div>
                                <div class="small text-muted">
                                    <span>Accedido el: </span> {{dateHuman(item.lastAccessDate,"d/m/Y H:i")}}hrs
                                </div>
                            </td>
                            <td class="d-none d-md-table-cell">
                                <div><a href="{{path('_profile',{'username':item.lastModifiedBy.username})}}">{{item.lastModifiedBy.username}}</a></div>
                                <div class="small text-muted">
                                    <span>Modificado el: </span> {{dateHuman(item.lastModifiedDate,"d/m/Y H:i")}}hrs
                                </div>
                            </td>
                            <td class="text-center">
                                <strong>
                                    <div class="d-xs-inline-table d-none">
                                        <div class="btn-group" role="group" file="{{item.encoded}}">
                                            {% if item.mark %}
                                                <button class="btn btn-dark" onclick="Mark(this);"><i class="fa fa-star fa-adapt"></i></button>
                                            {% else %}
                                                <button class="btn btn-dark" onclick="Mark(this);"><i class="fa fa-star-o fa-adapt"></i></button>
                                            {% endif %}
                                            {% if item.trash %}
                                                <button class="btn btn-dark" onclick="Recover(this);"><i class="icon-action-undo"></i></button>
                                            {% else %}
                                                <button class="btn btn-dark"onclick="Delete(this);"><i class="icon-trash"></i></button>
                                            {% endif  %}
                                        </div>
                                        <div class="btn-group" role="group" file="{{item.encoded}}">
                                            <button class="btn btn-dark" onclick="Share(this);"><i class="icon-share"></i></button>
                                            <button class="btn btn-dark"><i class="icon-calendar"></i></button>
                                        </div>
                                        <!--
                                        -->
                                    </div>
                                    <div class="dropdown d-xs-none">
                                        <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">&#9776;</button>
                                        <div class="dropdown-menu" aria-labelledby="dropdownMenuButton" file="{{item.encoded}}">
                                            <button class="dropdown-item" href="#">Añadir a favoritos</button>
                                            <button class="dropdown-item" href="#">Borrar</button>
                                            <button class="dropdown-item" href="#">Compartir</button>
                                            <button class="dropdown-item" href="#">Versiones</button>
                                        </div>
                                    </div>
                                </strong>
                            </td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    {% else %}
        <div class="jumbotron">
            <h1 class="display-3">Oops!</h1>
            <p class="lead">Aqui no hay archivos, pero puedes añadirlos haciendo click en destacar.</p>
            <picture>
                <source media="(min-width: 1024px)" srcset="{{asset('assets/img/help/add_fav_lg.png')}}">
                <source media="(min-width: 768px)" srcset="{{asset('assets/img/help/add_fav_md.png')}}">
                <source media="(min-width: 350px)" srcset="{{asset('assets/img/help/add_fav_sm.png')}}">
                <img class="img-fluid" src="{{asset('assets/img/help/add_fav_xs.png')}}" alt="" style="">
            </picture>
            <hr class="my-4">
        </div>
    {% endif %}
    <!--/.card-->
</div>

src/AppBundle/Resources/views/Main/trash.html.twig
{% include "::api.html.twig" %}
<script>
    var requireJS = [];
    loadJS(requireJS, "{{path('RAL',{'request':'upload.js'}) }}");
    loadJS(requireJS, "{{path('RAL',{'request':'api.js'}) }}");
</script>



<div class="animated fadeIn">
    {% if files is defined and files|length > 0 %}
        <div class="card">
            <table class="table table-responsive table-hover table-align-middle table-inverse table-striped mb-0">
                <thead class="thead-inverse">
                    <tr>
                        <th class="text-center"><i class="fa fa-lg fa-files-o"></i>
                        </th>
                        <th>Nombre</th>
                        <th class="text-center">Tamaño</th>
                        <th class="d-none d-md-table-cell">Tiempo de vida</th>
                        <th class="d-none d-md-table-cell">Fecha de borrado</th>
                        <th class="text-center"><i class="icon-grid"></i></th>
                    </tr>
                </thead>
                <tbody>
                    {% for item in files %}
                    <tr>
                        <td class="text-center" ondblclick="alert('hola');">
                            <i class=" fa fa-lg {{item.object.icon}}"></i>
                        </td>
                        <td ondblclick="alert('hola');">
                            <div>{{item.object.name}}</div>
                            <div class="small text-muted">
                                <span>Creado el: </span> {{dateHuman(item.object.creationDate,"d/m/Y H:i:s")}}
                            </div>
                        </td>
                        <td class="text-center">
                            <div class="callout callout-success">
                                <strong class="h6">{{bytesConvert(item.object.size)}}</strong>
                            </div>
                        </td>
                        <td class="d-none d-md-table-cell">
                            <div class="clearfix">
                                <div class="pull-left">
                                    <strong>Borrado permanente el: </strong>
                                </div>
                                <div class="pull-right">
                                    <small class="text-danger">{{dateHuman(item.trash.liveUntil,"d/m/Y H:i")}}hrs</small>
                                </div>
                            </div>
                            <div class="progress">
                                <div class="progress-bar bg-warning progress-bar-striped progress-bar-animated" role="progressbar" style="width: {{item.trash.livePercent}}%"></div>
                            </div>
                        </td>
                        <td class="d-none d-md-table-cell">
                            <div><a href="{{path('_profile',{'username':item.trash.deletedBy.username})}}">{{item.trash.deletedBy.username}}</a></div>
                            <div class="small text-muted">
                                <span class="text-warning">Borrado iniciado el: {{dateHuman(item.trash.deletedOn,"d/m/Y H:i:s")}}</span>
                            </div>
                        </td>
                        <td class="text-center">
                            <strong>
                                <div class="d-inline-table" file="{{item.object.encoded}}">
                                    <button class="btn btn-dark" onclick="Recover(this,true);"><i class="icon-action-undo"></i></button>
                                </div>
                            </strong>
                        </td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    {% else %}
        <div class="jumbotron">
            <h1 class="display-3">Oops!</h1>
            <p class="lead">Aqui no hay archivos, no se si sea bueno o malo, pero puedes mandarlos a borrar haciendo click en borrar.</p>
            <picture>
                <source media="(min-width: 1024px)" srcset="{{asset('assets/img/help/delete_lg.png')}}">
                <source media="(min-width: 768px)" srcset="{{asset('assets/img/help/delete_md.png')}}">
                <source media="(min-width: 350px)" srcset="{{asset('assets/img/help/delete_sm.png')}}">
                <img class="img-fluid" src="{{asset('assets/img/help/delete_xs.png')}}" alt="" style="">
            </picture>
            <hr class="my-4">
        </div>
    {% endif %}
    <!--/.card-->
</div>